### PR TITLE
Add -m for custom master, use SBT_HOME if set, Scala 2.11

### PR DESCRIPTION
**Pull request by a-roberts**
I've added -m and --master so we can use something other than local[*], let's still keep that as the default

I was having trouble with the sbt script so modified sbt-launch-lib.bash to check for a jar at $SBT_HOME

Also as we now specify Spark version 2.0.0 in the sbt project file I've upped the Scala version to match (2.11.8)

Tested by running with -m foo, -m local[*] and --master local[2] with

bin/run --benchmark DatasetPerformance _then the master options_

### CODE REVIEW

**Comment by a-roberts** [comment]
Anybody there to review/merge this?

**Comment by a-roberts** [comment]
Any update here please? This change makes it convenient for users to run the benchmark against a cluster without modifying the code and rebuilding

**Comment by npoggi** [comment]
@a-roberts could you rebase this commit and add me as the reviewer to finally getting this PR merged?  Thanks

**Comment by a-roberts** [comment]
Sorry @npoggi, haven't worked on Spark for years now, should be simple enough for anybody else to pick up though!

**Comment by npoggi** [comment]
Ok, created a different PR with a rebase merging relevant parts.  Thanks @a-roberts, see (PR 169)[https://github.com/databricks/spark-sql-perf/pull/169]

**Pull request closed without merging**
