### PR TITLE
Update for Spark 3.0.0 compatibility

### PR DESCRIPTION
**Pull request by npoggi**
- Updating the build file to spark 3.0.0 and scala 2.12.10
- Fixing incompatibilities
- Adding default parameters to newer required functions
- Removing HiveTest

### CODE REVIEW

**Comment by npoggi** [comment]
@yashkv1 test it out when you can

**Comment by yashkv1** [comment]
> @yashkv1 test it out when you can

@npoggi  - It compiles with few warnings.  [warn] Multiple main classes detected.  Run 'show discoveredMainClasses' to see the list

I will test the jar and post here in a couple of days. Thank you 👍

**Comment by yashkv1** [comment]
> @yashkv1 were you able to test the jar?

@npoggi  - yes. changes you made works. Tested with Spark 3.0.0.

**Comment by v33ran00l** [comment]
> > @yashkv1 were you able to test the jar?
> 
> @npoggi - yes. changes you made works. Tested with Spark 3.0.0.

HI Yashkv1 : i'm trying to test this and failed, please can you help on this, how to create with spark3, please share if you have any document how to test create and test this.

**Comment by npoggi** [comment]
@yashkv1 what is the output of `spark-sql-perf/build/sbt assembly`?

**Comment by npoggi** [comment]
@v33ran00l what is the output of `spark-sql-perf/build/sbt assembly`?

**Comment by v33ran00l** [comment]
Hi thanks able to run after changing scala n spark version in build.sbt

**Review by Loquats — APPROVED** [review]
ML-related changes LGTM. I tested this branch on ML pipelines used in perf tests, and things are working as expected.

**Comment by npoggi** [comment]
Thanks for the review @Loquats

**Pull request merged**
